language: rust
rust:
- nightly
- beta
- stable
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
before_deploy:
- cargo doc --verbose
- cargo package --verbose
  file: target/package/slack-${TRAVIS_TAG:1}.crate
  skip_cleanup: true
  on:
    repo: slack-rs/slack-rs
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable"
