[package]
name = "slack"
version = "0.13.0"
authors = ["Benjamin Elder <bentheelder@gmail.com>", "Matt Jones <mthjones@gmail.com>"]
repository = "https://github.com/BenTheElder/slack-rs.git"
documentation = "https://bentheelder.github.io/slack-rs"
description = "slack realtime messaging client: https://api.slack.com/bot-users"
license = "Apache-2.0"

[dependencies]
websocket = "0.15.2"
hyper = "0.8.0"
rustc-serialize = "0.3.18"

[dev-dependencies]
yup-hyper-mock = "1.3.2"
log = "0.3.5"
